import { Product, ProductType } from '@tirehub/shared';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    sku: 'MIC-PILOT-205-55-R16',
    name: 'Michelin Pilot Sport 4',
    type: ProductType.TIRE,
    price: 8990,
    stockQuantity: 42,
    brand: 'Michelin',
    rating: 4.8,
    imageUrl: '/images/products/michelin-pilot-sport-4.jpg',
  },
  {
    id: 'prod-002',
    sku: 'NOK-HAKKA-205-55-R16',
    name: 'Nokian Hakka Blue 3',
    type: ProductType.TIRE,
    price: 6490,
    stockQuantity: 28,
    brand: 'Nokian',
    rating: 4.6,
    imageUrl: '/images/products/nokian-hakka-blue-3.jpg',
  },
  {
    id: 'prod-003',
    sku: 'CON-WINTER-205-55-R16',
    name: 'Continental WinterContact TS 870',
    type: ProductType.TIRE,
    price: 7290,
    stockQuantity: 35,
    brand: 'Continental',
    rating: 4.7,
    imageUrl: '/images/products/continental-wintercontact.jpg',
  },
  {
    id: 'prod-004',
    sku: 'BRID-BLZ-205-55-R16',
    name: 'Bridgestone Blizzak LM005',
    type: ProductType.TIRE,
    price: 7890,
    stockQuantity: 19,
    brand: 'Bridgestone',
    rating: 4.9,
    imageUrl: '/images/products/bridgestone-blizzak.jpg',
  },
  {
    id: 'prod-005',
    sku: 'GOOD-AS-205-55-R16',
    name: 'Goodyear Vector 4Seasons Gen-3',
    type: ProductType.TIRE,
    price: 6990,
    stockQuantity: 51,
    brand: 'Goodyear',
    rating: 4.5,
    imageUrl: '/images/products/goodyear-vector.jpg',
  },
  {
    id: 'prod-006',
    sku: 'YOKO-ADV-205-55-R16',
    name: 'Yokohama Advan Sport V105',
    type: ProductType.TIRE,
    price: 8490,
    stockQuantity: 14,
    brand: 'Yokohama',
    rating: 4.4,
    imageUrl: '/images/products/yokohama-advan.jpg',
  },
  {
    id: 'prod-007',
    sku: 'PIRE-PZ4-205-55-R16',
    name: 'Pirelli P Zero PZ4',
    type: ProductType.TIRE,
    price: 9490,
    stockQuantity: 22,
    brand: 'Pirelli',
    rating: 4.7,
    imageUrl: '/images/products/pirelli-pzero.jpg',
  },
  {
    id: 'prod-008',
    sku: 'HANK-KIN-205-55-R16',
    name: 'Hankook Kinergy 4S2',
    type: ProductType.TIRE,
    price: 5790,
    stockQuantity: 67,
    brand: 'Hankook',
    rating: 4.3,
    imageUrl: '/images/products/hankook-kinergy.jpg',
  },
];
