import { ProductType, TireSeason } from '@tirehub/shared';

export interface CatalogProduct {
  id: string;
  sku: string;
  name: string;
  type: ProductType;
  price: number;
  stockQuantity: number;
  imageUrl: string;
  brand: string;
  rating: number;
  attributes: {
    width?: number;
    profile?: number;
    diameter?: number;
    pcd?: string;
    offsetEt?: number;
    season?: TireSeason;
    boltCount?: number;
  };
}

/** Real photos from Wikimedia Commons (downloaded locally for speed). */
export const TIRE_IMAGES = {
  michelin: '/images/products/tire-michelin.jpg',
  pirelli: '/images/products/tire-pirelli.jpg',
  bridgestone: '/images/products/tire-bridgestone.jpg',
  bridgestone2: '/images/products/tire-bridgestone-2.jpg',
  falken: '/images/products/tire-falken.jpg',
  yokohama: '/images/products/tire-yokohama.jpg',
  closeup: '/images/products/tire-closeup.jpg',
  honda: '/images/products/tire-honda.jpg',
  nascar: '/images/products/tire-nascar.jpg',
  // aliases for older refs
  sport: '/images/products/tire-michelin.jpg',
  classic: '/images/products/tire-honda.jpg',
  black: '/images/products/tire-pirelli.jpg',
  tread: '/images/products/tire-closeup.jpg',
  stack: '/images/products/tire-yokohama.jpg',
  winter: '/images/products/tire-bridgestone.jpg',
  premium: '/images/products/tire-bridgestone-2.jpg',
  detail: '/images/products/tire-falken.jpg',
  workshop: '/images/products/tire-nascar.jpg',
  road: '/images/products/tire-honda.jpg',
} as const;

export const WHEEL_IMAGES = {
  bbs1: '/images/products/wheel-bbs-1.jpg',
  bbs2: '/images/products/wheel-bbs-2.jpg',
  bbs3: '/images/products/wheel-bbs-3.jpg',
  bbs4: '/images/products/wheel-bbs-4.jpg',
  bbs5: '/images/products/wheel-bbs-5.jpg',
  bbs6: '/images/products/wheel-bbs-6.jpg',
  bbsGt86: '/images/products/wheel-bbs-gt86.jpg',
  forged: '/images/products/wheel-forged.jpg',
  gtr: '/images/products/wheel-gtr.jpg',
  bmw: '/images/products/wheel-bmw.jpg',
  mazda: '/images/products/wheel-mazda.jpg',
  copen: '/images/products/wheel-copen.jpg',
  porsche: '/images/products/wheel-porsche-cup.jpg',
  z4: '/images/products/wheel-z4.jpg',
  trx: '/images/products/wheel-trx.jpg',
  // aliases
  silver: '/images/products/wheel-bmw.jpg',
  chrome: '/images/products/wheel-gtr.jpg',
  sport: '/images/products/wheel-bbs-gt86.jpg',
  alloy: '/images/products/wheel-mazda.jpg',
  black: '/images/products/wheel-porsche-cup.jpg',
  multi: '/images/products/wheel-bbs-2.jpg',
  matte: '/images/products/wheel-copen.jpg',
  replica: '/images/products/wheel-bbs-1.jpg',
  premium: '/images/products/wheel-forged.jpg',
} as const;

export const mockProducts: CatalogProduct[] = [
  // —— Шины ——
  {
    id: '1',
    sku: 'TIR-001',
    name: 'Michelin Pilot Sport 4S 245/35 R19',
    type: ProductType.TIRE,
    price: 18900,
    stockQuantity: 28,
    imageUrl: TIRE_IMAGES.michelin,
    brand: 'Michelin',
    rating: 4.9,
    attributes: { width: 245, profile: 35, diameter: 19, season: TireSeason.SUMMER },
  },
  {
    id: '2',
    sku: 'TIR-002',
    name: 'Pirelli Cinturato P7 225/45 R17',
    type: ProductType.TIRE,
    price: 11200,
    stockQuantity: 40,
    imageUrl: TIRE_IMAGES.pirelli,
    brand: 'Pirelli',
    rating: 4.7,
    attributes: { width: 225, profile: 45, diameter: 17, season: TireSeason.SUMMER },
  },
  {
    id: '3',
    sku: 'TIR-003',
    name: 'Bridgestone Potenza Sport 255/40 R18',
    type: ProductType.TIRE,
    price: 15400,
    stockQuantity: 22,
    imageUrl: TIRE_IMAGES.bridgestone,
    brand: 'Bridgestone',
    rating: 4.8,
    attributes: { width: 255, profile: 40, diameter: 18, season: TireSeason.SUMMER },
  },
  {
    id: '4',
    sku: 'TIR-004',
    name: 'Bridgestone Blizzak LM005 205/55 R16',
    type: ProductType.TIRE,
    price: 9800,
    stockQuantity: 36,
    imageUrl: TIRE_IMAGES.bridgestone2,
    brand: 'Bridgestone',
    rating: 4.8,
    attributes: { width: 205, profile: 55, diameter: 16, season: TireSeason.WINTER },
  },
  {
    id: '5',
    sku: 'TIR-005',
    name: 'Yokohama ADVAN Neova AD08R 225/40 R18',
    type: ProductType.TIRE,
    price: 13200,
    stockQuantity: 18,
    imageUrl: TIRE_IMAGES.yokohama,
    brand: 'Yokohama',
    rating: 4.6,
    attributes: { width: 225, profile: 40, diameter: 18, season: TireSeason.SUMMER },
  },
  {
    id: '6',
    sku: 'TIR-006',
    name: 'Yokohama BluEarth A/S 215/55 R17',
    type: ProductType.TIRE,
    price: 8600,
    stockQuantity: 48,
    imageUrl: TIRE_IMAGES.honda,
    brand: 'Yokohama',
    rating: 4.5,
    attributes: { width: 215, profile: 55, diameter: 17, season: TireSeason.ALL_SEASON },
  },
  {
    id: '7',
    sku: 'TIR-007',
    name: 'Falken Azenis FK520 245/40 R19',
    type: ProductType.TIRE,
    price: 12100,
    stockQuantity: 20,
    imageUrl: TIRE_IMAGES.falken,
    brand: 'Falken',
    rating: 4.6,
    attributes: { width: 245, profile: 40, diameter: 19, season: TireSeason.SUMMER },
  },
  {
    id: '8',
    sku: 'TIR-008',
    name: 'Continental PremiumContact 7 235/45 R18',
    type: ProductType.TIRE,
    price: 14500,
    stockQuantity: 30,
    imageUrl: TIRE_IMAGES.closeup,
    brand: 'Continental',
    rating: 4.8,
    attributes: { width: 235, profile: 45, diameter: 18, season: TireSeason.SUMMER },
  },
  {
    id: '9',
    sku: 'TIR-009',
    name: 'Nokian Hakkapeliitta R5 225/50 R17',
    type: ProductType.TIRE,
    price: 13900,
    stockQuantity: 24,
    imageUrl: TIRE_IMAGES.nascar,
    brand: 'Nokian',
    rating: 4.9,
    attributes: { width: 225, profile: 50, diameter: 17, season: TireSeason.WINTER },
  },
  {
    id: '10',
    sku: 'TIR-010',
    name: 'Goodyear Eagle F1 Asymmetric 6 255/35 R19',
    type: ProductType.TIRE,
    price: 17200,
    stockQuantity: 16,
    imageUrl: TIRE_IMAGES.michelin,
    brand: 'Goodyear',
    rating: 4.7,
    attributes: { width: 255, profile: 35, diameter: 19, season: TireSeason.SUMMER },
  },

  // —— Диски: BBS, HRE, Vossen, OZ, Enkei, Rays… ——
  {
    id: '11',
    sku: 'WHL-BBS-01',
    name: 'BBS CH-R 8.5x19 5x112 ET32',
    type: ProductType.WHEEL,
    price: 68500,
    stockQuantity: 8,
    imageUrl: WHEEL_IMAGES.bbs1,
    brand: 'BBS',
    rating: 4.9,
    attributes: { diameter: 19, pcd: '5x112', offsetEt: 32, boltCount: 5 },
  },
  {
    id: '12',
    sku: 'WHL-BBS-02',
    name: 'BBS LM 9x20 5x120 ET25',
    type: ProductType.WHEEL,
    price: 92000,
    stockQuantity: 4,
    imageUrl: WHEEL_IMAGES.bbs2,
    brand: 'BBS',
    rating: 5.0,
    attributes: { diameter: 20, pcd: '5x120', offsetEt: 25, boltCount: 5 },
  },
  {
    id: '13',
    sku: 'WHL-BBS-03',
    name: 'BBS RI-A 8x18 5x114.3 ET45',
    type: ProductType.WHEEL,
    price: 54800,
    stockQuantity: 10,
    imageUrl: WHEEL_IMAGES.bbs3,
    brand: 'BBS',
    rating: 4.8,
    attributes: { diameter: 18, pcd: '5x114.3', offsetEt: 45, boltCount: 5 },
  },
  {
    id: '14',
    sku: 'WHL-BBS-04',
    name: 'BBS FI-R Forged 10x20 5x130 ET50',
    type: ProductType.WHEEL,
    price: 125000,
    stockQuantity: 2,
    imageUrl: WHEEL_IMAGES.bbsGt86,
    brand: 'BBS',
    rating: 5.0,
    attributes: { diameter: 20, pcd: '5x130', offsetEt: 50, boltCount: 5 },
  },
  {
    id: '15',
    sku: 'WHL-HRE-01',
    name: 'HRE P101 Forged 9x19 5x112 ET35',
    type: ProductType.WHEEL,
    price: 145000,
    stockQuantity: 3,
    imageUrl: WHEEL_IMAGES.gtr,
    brand: 'HRE',
    rating: 5.0,
    attributes: { diameter: 19, pcd: '5x112', offsetEt: 35, boltCount: 5 },
  },
  {
    id: '16',
    sku: 'WHL-HRE-02',
    name: 'HRE S101 FlowForm 8.5x20 5x120 ET30',
    type: ProductType.WHEEL,
    price: 98000,
    stockQuantity: 5,
    imageUrl: WHEEL_IMAGES.z4,
    brand: 'HRE',
    rating: 4.9,
    attributes: { diameter: 20, pcd: '5x120', offsetEt: 30, boltCount: 5 },
  },
  {
    id: '17',
    sku: 'WHL-HRE-03',
    name: 'HRE FF01 9.5x19 5x114.3 ET40',
    type: ProductType.WHEEL,
    price: 87000,
    stockQuantity: 6,
    imageUrl: WHEEL_IMAGES.porsche,
    brand: 'HRE',
    rating: 4.9,
    attributes: { diameter: 19, pcd: '5x114.3', offsetEt: 40, boltCount: 5 },
  },
  {
    id: '18',
    sku: 'WHL-VOSSEN-01',
    name: 'Vossen HF-5 9x20 5x112 ET28',
    type: ProductType.WHEEL,
    price: 78000,
    stockQuantity: 7,
    imageUrl: WHEEL_IMAGES.bbs5,
    brand: 'Vossen',
    rating: 4.8,
    attributes: { diameter: 20, pcd: '5x112', offsetEt: 28, boltCount: 5 },
  },
  {
    id: '19',
    sku: 'WHL-OZ-01',
    name: 'OZ Racing Ultraleggera 8x18 5x100 ET35',
    type: ProductType.WHEEL,
    price: 42500,
    stockQuantity: 12,
    imageUrl: WHEEL_IMAGES.bbs4,
    brand: 'OZ Racing',
    rating: 4.8,
    attributes: { diameter: 18, pcd: '5x100', offsetEt: 35, boltCount: 5 },
  },
  {
    id: '20',
    sku: 'WHL-OZ-02',
    name: 'OZ Racing Leggera HLT 9x19 5x120 ET40',
    type: ProductType.WHEEL,
    price: 56200,
    stockQuantity: 8,
    imageUrl: WHEEL_IMAGES.bbs6,
    brand: 'OZ Racing',
    rating: 4.7,
    attributes: { diameter: 19, pcd: '5x120', offsetEt: 40, boltCount: 5 },
  },
  {
    id: '21',
    sku: 'WHL-ENKEI-01',
    name: 'Enkei RPF1 8.5x18 5x114.3 ET35',
    type: ProductType.WHEEL,
    price: 28900,
    stockQuantity: 16,
    imageUrl: WHEEL_IMAGES.forged,
    brand: 'Enkei',
    rating: 4.9,
    attributes: { diameter: 18, pcd: '5x114.3', offsetEt: 35, boltCount: 5 },
  },
  {
    id: '22',
    sku: 'WHL-RAYS-01',
    name: 'Rays Volk Racing TE37 9x18 5x114.3 ET22',
    type: ProductType.WHEEL,
    price: 115000,
    stockQuantity: 4,
    imageUrl: WHEEL_IMAGES.bmw,
    brand: 'Rays',
    rating: 5.0,
    attributes: { diameter: 18, pcd: '5x114.3', offsetEt: 22, boltCount: 5 },
  },
  {
    id: '23',
    sku: 'WHL-WORK-01',
    name: 'Work Emotion CR Kiwami 9x18 5x100 ET38',
    type: ProductType.WHEEL,
    price: 52000,
    stockQuantity: 6,
    imageUrl: WHEEL_IMAGES.mazda,
    brand: 'Work',
    rating: 4.7,
    attributes: { diameter: 18, pcd: '5x100', offsetEt: 38, boltCount: 5 },
  },
  {
    id: '24',
    sku: 'WHL-ROTIFORM-01',
    name: 'Rotiform RSE 8.5x19 5x112 ET45',
    type: ProductType.WHEEL,
    price: 41000,
    stockQuantity: 9,
    imageUrl: WHEEL_IMAGES.copen,
    brand: 'Rotiform',
    rating: 4.6,
    attributes: { diameter: 19, pcd: '5x112', offsetEt: 45, boltCount: 5 },
  },
  {
    id: '25',
    sku: 'WHL-BBS-05',
    name: 'BBS XR 8x17 5x112 ET30',
    type: ProductType.WHEEL,
    price: 38900,
    stockQuantity: 14,
    imageUrl: WHEEL_IMAGES.trx,
    brand: 'BBS',
    rating: 4.7,
    attributes: { diameter: 17, pcd: '5x112', offsetEt: 30, boltCount: 5 },
  },
];

export const PCD_OPTIONS = ['4x100', '5x100', '5x108', '5x112', '5x114.3', '5x120', '5x130'] as const;

export const FILTER_WIDTHS = [185, 195, 205, 215, 225, 235, 245, 255];
export const FILTER_PROFILES = [35, 40, 45, 50, 55, 60, 65];
export const FILTER_DIAMETERS = [16, 17, 18, 19, 20];

export function getProductById(id: string) {
  return mockProducts.find((p) => p.id === id);
}
